### Login
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "resame@gmail.com",
    "password": "Motdepasse12@@",
    "otp": ""
}

### Signup
POST http://127.0.0.1:8000/api/auth/signup/
Content-Type: application/json

{
    "username": "bil",
    "password": "Motdepasse12@@",
    "password2": "Motdepasse12@@",
    "email": "resame@gmail.com"
}

### Refresh Token
POST http://127.0.0.1:8000/api/auth/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTQzNDIzOSwiaWF0IjoxNzMxMzQ3ODM5LCJqdGkiOiJmNDkzM2IwN2JmZTI0OTk2OTA4YjYyNWZhODA2MDEyZiIsInVzZXJfaWQiOjJ9.GqyLPvhYAN4mVJ9Jh7T9ZJrd7SEMNjgyDLifH_WUmes"
}

### Request Password Reset
POST http://127.0.0.1:8000/api/auth/password/reset/
Content-Type: application/json

{
    "email": "reset.pass.ponggame@gmail.com"
}

### Confirm Password Reset
POST http://127.0.0.1:8000/api/auth/password/reset/confirm/Mg/cfnhn8-6526e51095b178fa8d48f420e5b2e6bc/
Content-Type: application/json

{
    "new_password": "palestin"
}

### Confirm Password Reset

POST http://127.0.0.1:8000/api/auth/password/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxNDM1NTYwLCJpYXQiOjE3MzE0MzE5NjAsImp0aSI6ImUzMTkzNjY4MmViZTQzMGI4OWQzZDg1OGI1NTA4ZjUxIiwidXNlcl9pZCI6Mn0.L4uzPIEMGVoc3VpUm71EmBRmhybjVdAQrHg5A71nSrc

{
    "old_password": "Palestine93@",
    "new_password": "Azerty93@"
}
### Logout
POST http://127.0.0.1:8000/api/auth/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjk1MTYwLCJpYXQiOjE3MzAyOTE1NjAsImp0aSI6IjRkNWJhN2NlYTQxZDRiMzhiNzI5ZjQyM2NkYjY2ZjhjIiwidXNlcl9pZCI6Mn0.-1EBA11nqoOzgtH0kYbQj-XG8HusprnZPGdHYdaYPkI

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMDM3Nzk2MCwiaWF0IjoxNzMwMjkxNTYwLCJqdGkiOiI4NjUxMTZiOGNkOWQ0NDFjOTk2MGVjMzM5Nzk3ODQ2MiIsInVzZXJfaWQiOjJ9.W3mlpN2hspwNetdVEeoqq0ttZ_kFO65lV-IdcMS1uCQ"
}

### Token verify

POST http://127.0.0.1:8000/api/auth/token/validate/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxNDM1NTYwLCJpYXQiOjE3MzE0MzE5NjAsImp0aSI6ImUzMTkzNjY4MmViZTQzMGI4OWQzZDg1OGI1NTA4ZjUxIiwidXNlcl9pZCI6Mn0.L4uzPIEMGVoc3VpUm71EmBRmhybjVdAQrHg5A71nSrc
###
POST http://127.0.0.1:8000/api/auth/users/info/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyMTk1NDYwLCJpYXQiOjE3MzIxOTE4NjAsImp0aSI6IjJhNjg0NTk2OGU5MzQ3YzhiZjIwN2FiMjA0NDhjYjFlIiwidXNlcl9pZCI6Mn0.eaa0L0nxVR4fQ86bTFQoFqqH4yPI4s2zlfgI9zK9Ev0

{
    "user_ids": [1]
}

### 2FA

GET http://127.0.0.1:8000/api/auth/2fa/enable/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxOTUzNTY3LCJpYXQiOjE3MzE5NDk5NjcsImp0aSI6IjU1ODBmZmM2OWI5NjQwNDY5NGRkZjhmZDM1OTFlYjY5IiwidXNlcl9pZCI6Mn0.O_sJEk5LbjnK8wNLNzHWazseDOFzE5_gLn1LZsxX9LQ

###

DELETE http://127.0.0.1:8000/api/auth/2fa/disable/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxOTUzNTExLCJpYXQiOjE3MzE5NDk5MTEsImp0aSI6IjA3MDlkYWM5YWQ3MDQ3YTRiNTBjN2VjZWU0NjNkNmE1IiwidXNlcl9pZCI6Mn0._e4EcQx9YEeedXz6jmwDRwWYSeGc3ksA2HPfhsU4DRI

###
POST http://127.0.0.1:8000/api/auth/2fa/verify/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxNTA3ODU1LCJpYXQiOjE3MzE1MDQyNTUsImp0aSI6IjAzOTZiNzQ5ZGExMDRhOGI4ZTA4MDZkZjBlOThmNThkIiwidXNlcl9pZCI6Mn0.RW4Jqxnn8p-I3vcCBiGQZdC3sIP83dSciCpmAb4FNDo