POST https://localhost:8443/usermanagement/matches/create/
Content-Type: application/json

{
    "player_1_id": 2,
    "player_2_id": 3,
    "match_start_time": "2023-11-27T10:00:00Z",
    "match_end_time": "2023-11-27T12:00:00Z",
    "score_player_1": 10,
    "score_player_2": 15
}

###
GET https://sxpongo.ddns.net:8443/usermanagement/2/matches/

###

POST https://localhost:8443/usermanagement/friends/request/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzQ3ODM1LCJpYXQiOjE3Mzg3NDQyMzUsImp0aSI6IjQ5MjEzM2I0YjFjOTQzNGNiYmQ4YzdlNWUyZWY2NWIyIiwidXNlcl9pZCI6Mn0.S_OQ5z65UlJGETLGCi-c5rMYoVE0NHM3M95m7QVBdcc

{
  "friend_id": 3
}

###
POST http://127.0.0.1:8001/usermanagement/friends/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODgxNzM4LCJpYXQiOjE3MzI4NzgxMzgsImp0aSI6Ijk4NTUyNGE1OTExMzQ3OWU4ZWEwNWZlMzY0ZWVhZThjIiwidXNlcl9pZCI6M30.dmKvZEWhL93snrXg1Fflfl3qgAz727HzWN_kZogQ_I0

{
  "friend_id": 4,
  "status": "accepted"
}
###
GET https://xpongo.myddns.me:8443/usermanagement/friends/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NDY2Njg3LCJpYXQiOjE3Mzk0NjMwODcsImp0aSI6Ijc3YWEwZjVjNjE1YTQ5NWE5YmNjYjBkNDk2N2Q5NDMyIiwidXNlcl9pZCI6MX0.CTgi4r3fAPrlFAymd57wQQ0cereC2lTTzK1RMTxOq-Q

###

POST https://localhost:8443/usermanagement/block/request/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODg2ODI2LCJpYXQiOjE3MzI4ODMyMjYsImp0aSI6ImVlODc5OTMwYjhjNjQ5NjM4MTgwMWQ5ZmZhNTRmNWY3IiwidXNlcl9pZCI6Mn0.lAWc_AIATAlFqdm7IEZabFw9Kq_L2IZqU_7ZX9vNvPI

{
  "user_to_block": 4
}
###
GET https://localhost:8443/usermanagement/block/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4ODM5NzA3LCJpYXQiOjE3Mzg4MzYxMDcsImp0aSI6ImI4ZGI4MTdjZmJmMDQwNDU4ZTY5MmRiMGZmMTNkMmRkIiwidXNlcl9pZCI6Mn0.2gvSahqsK3BaX561LJhni4pJvalVTB8ONshwuolaRqs

###
POST https://localhost:8443/usermanagement/unblock/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4ODM2ODc5LCJpYXQiOjE3Mzg4MzMyNzksImp0aSI6IjExYjFiZTQ2MWVlYjRiODNiYmI2NmRjNDg3ODBkNzc3IiwidXNlcl9pZCI6M30.cLdN4lFFrW75f7Peb5fLpYK0IJBaZjOa9LmaRR-nqFE

{
  "user_to_unblock": 2
}

###
GET https://localhost:8443/usermanagement/friends/listrequests/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzQ3MjIzLCJpYXQiOjE3Mzg3NDM2MjMsImp0aSI6IjhhZGZmMzMwZTgyNTRlZGI5N2U3MWQxYWZhMTFiNjBiIiwidXNlcl9pZCI6M30.DOULf-VP1LBIN7oedY72YWbMepfrVD0ru0Pje4RtYiY