POST http://127.0.0.1:8001/user/matches/create/
Content-Type: application/json

{
    "player_1_id": 2,
    "player_2_id": 3,
    "match_start_time": "2024-11-27T10:00:00Z",
    "match_end_time": "2024-11-27T12:00:00Z",
    "score_player_1": 10,
    "score_player_2": 15
}

###
GET http://127.0.0.1:8001/user/3/matches/

###

POST http://127.0.0.1:8001/user/friends/request/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzYwODkxLCJpYXQiOjE3MzI3NTcyOTEsImp0aSI6Ijk0M2NmYjkwZTYxNzQ5NzM4OTllNTIyYTBiYmJhOWEyIiwidXNlcl9pZCI6Mn0.T6OykBUgtlacqF3GMxGn1C8ZO4ydoWmPhEqSWk52A48

{
  "friend_id": 3
}

###
POST http://127.0.0.1:8001/user/friends/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzYxMTQ1LCJpYXQiOjE3MzI3NTc1NDUsImp0aSI6IjQxNDE4ODNjNzRmOTQzNDNiYTYwNzdhMzlhZjgzMTgwIiwidXNlcl9pZCI6M30.Bd31EIXrgV8l4rbOOSzPaYGPuzqbsJZdW2GWoILznNY

{
  "friend_id": 2,
  "status": "blocked"
}