POST http://127.0.0.1:8001/user/matches/create/
Content-Type: application/json

{
    "player_1_id": 2,
    "player_2_id": 3,
    "match_start_time": "2024-11-27T10:00:00Z",
    "match_end_time": "2024-11-27T12:00:00Z",
    "score_player_1": 10,
    "score_player_2": 15
}

###
GET http://127.0.0.1:8001/user/3/matches/

###

POST http://127.0.0.1:8001/user/friends/request/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODgxNzAxLCJpYXQiOjE3MzI4NzgxMDEsImp0aSI6IjE0NTY1NjlkYzQwYjRmZTA5ZmI0YjNkNDU2MDc1MDY3IiwidXNlcl9pZCI6NH0.oBIwgRXLybYrZUSFLExHW97MZpA5gNtkfJmXONAMcDw

{
  "friend_id": 3
}

###
POST http://127.0.0.1:8001/user/friends/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODgxNzM4LCJpYXQiOjE3MzI4NzgxMzgsImp0aSI6Ijk4NTUyNGE1OTExMzQ3OWU4ZWEwNWZlMzY0ZWVhZThjIiwidXNlcl9pZCI6M30.dmKvZEWhL93snrXg1Fflfl3qgAz727HzWN_kZogQ_I0

{
  "friend_id": 4,
  "status": "accepted"
}
###
GET http://127.0.0.1:8001/user/friends/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODgxNzM4LCJpYXQiOjE3MzI4NzgxMzgsImp0aSI6Ijk4NTUyNGE1OTExMzQ3OWU4ZWEwNWZlMzY0ZWVhZThjIiwidXNlcl9pZCI6M30.dmKvZEWhL93snrXg1Fflfl3qgAz727HzWN_kZogQ_I0

###

POST http://127.0.0.1:8001/user/block/request/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODg2ODI2LCJpYXQiOjE3MzI4ODMyMjYsImp0aSI6ImVlODc5OTMwYjhjNjQ5NjM4MTgwMWQ5ZmZhNTRmNWY3IiwidXNlcl9pZCI6Mn0.lAWc_AIATAlFqdm7IEZabFw9Kq_L2IZqU_7ZX9vNvPI

{
  "user_to_block": 4
}
###
GET http://127.0.0.1:8001/user/block/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODg2ODI2LCJpYXQiOjE3MzI4ODMyMjYsImp0aSI6ImVlODc5OTMwYjhjNjQ5NjM4MTgwMWQ5ZmZhNTRmNWY3IiwidXNlcl9pZCI6Mn0.lAWc_AIATAlFqdm7IEZabFw9Kq_L2IZqU_7ZX9vNvPI

###
POST http://127.0.0.1:8001/user/unblock/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODg3ODg4LCJpYXQiOjE3MzI4ODQyODgsImp0aSI6ImZiZmM2YjI1YWNkYjQ5YjM4Y2JkYzgxNWJiZTYzMjg2IiwidXNlcl9pZCI6Mn0.bT1lz30-IVIZSCI4sNEym8hyNoMgWvdg7hmblAKf9KM

{
  "user_to_unblock": 3
}