# Generated by Django 5.1.2 on 2024-11-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementService', '0003_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_1_history', to='UserManagementService.userprofile'),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_2_history', to='UserManagementService.userprofile'),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches_history', to='UserManagementService.userprofile'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_start_time', models.DateTimeField(blank=True, null=True)),
                ('match_end_time', models.DateTimeField(blank=True, null=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_1', to='UserManagementService.userprofile')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player_2', to='UserManagementService.userprofile')),
            ],
        ),
    ]
