# Generated by Django 5.1.2 on 2024-11-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementService', '0004_alter_matchhistory_player_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='confirmed_by_player_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='confirmed_by_player_2',
            field=models.BooleanField(default=False),
        ),
    ]
