# Generated by Django 5.1.2 on 2024-11-05 14:44

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_rename_username_userprofileimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=media.models.unique_filename_username),
        ),
    ]
