# Generated by Django 5.1.2 on 2024-11-06 14:53

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_userprofileimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='image',
            field=models.ImageField(null=True, upload_to=media.models.unique_filename_username),
        ),
    ]
