services:
  remote:
    build:
      context: ./docker
    volumes:
      - .:/app
      # - ./docker:/app/docker
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    env_file:
      - ../.env
    networks:
      my_network:
        aliases:
          - remote
    entrypoint: ["/app/docker/entrypoint_dev.sh"]

networks:
  my_network:
    external: true