services:

  mediaservice:
    build:
      context: docker/
      # dockerfile: mediaService/docker/Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

volumes:
  postgres_data:
