### Login
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "bileel",
    "password": "Algerie93"
}

### Signup
POST http://127.0.0.1:8000/api/auth/signup/
Content-Type: application/json

{
    "username": "bileel",
    "password": "Algerie93",
    "password2": "Algerie93",
    "email": "reset.pass.ponggame@gmail.com"
}

### Refresh Token
POST http://127.0.0.1:8000/api/auth/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwNDk2MzI5LCJpYXQiOjE3MzA0OTI3MjksImp0aSI6ImNkMmFjNTc0OGFjNjRhNTM4MDkxNzdkZTQ4NTViMjY1IiwidXNlcl9pZCI6Mn0.khymj6GK9Svx1uHwBfvJL4bQtnf9f8r5sIzfzNkoUjs"
}

### Request Password Reset
POST http://127.0.0.1:8000/api/auth/password/reset/
Content-Type: application/json

{
    "email": "reset.pass.ponggame@gmail.com"
}

### Confirm Password Reset
POST http://127.0.0.1:8000/api/auth/password/reset/confirm/Mg/cfnhn8-6526e51095b178fa8d48f420e5b2e6bc/
Content-Type: application/json

{
    "new_password": "palestin"
}

### Confirm Password Reset
POST http://127.0.0.1:8000/api/auth/password/change/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjE5NDM4LCJpYXQiOjE3MzAyMTU4MzgsImp0aSI6IjkwYjYyOTFiYzY5YjRjODlhYzViNTlkNGJjYTFmNzgyIiwidXNlcl9pZCI6MX0.dfoBLpa6WHpZt4T9Qoi2NJuRbaPs6DyJo6wHJe3nHzc

{
    "old_password": "Algerie93",
    "new_password": "palestine"
}

### Logout
POST http://127.0.0.1:8000/api/auth/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjk1MTYwLCJpYXQiOjE3MzAyOTE1NjAsImp0aSI6IjRkNWJhN2NlYTQxZDRiMzhiNzI5ZjQyM2NkYjY2ZjhjIiwidXNlcl9pZCI6Mn0.-1EBA11nqoOzgtH0kYbQj-XG8HusprnZPGdHYdaYPkI

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMDM3Nzk2MCwiaWF0IjoxNzMwMjkxNTYwLCJqdGkiOiI4NjUxMTZiOGNkOWQ0NDFjOTk2MGVjMzM5Nzk3ODQ2MiIsInVzZXJfaWQiOjJ9.W3mlpN2hspwNetdVEeoqq0ttZ_kFO65lV-IdcMS1uCQ"
}

### Token verify

POST http://127.0.0.1:8000/api/auth/token/validate/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwNDg3MDU0LCJpYXQiOjE3MzA0ODM0NTQsImp0aSI6ImYwNmU4YTY1NWZiMzRhM2RiNDNlYzg2NTZiZTFjYmM1IiwidXNlcl9pZCI6Mn0.4MAR0jSykY25QfuSBQBcP6PSrKf9HSk2BEzYhXLQ5aw

###
