### Établir une connexion WebSocket
GET ws://127.0.0.1:8000/ws/some_path/
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13

### Login HTTP (à faire avant la connexion WebSocket si authentification requise)
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "bilel.moudache0412@gmail.com",
    "password": "Algerie93@"
}

### Connexion WebSocket avec token (si vous utilisez l'authentification par token)
GET ws://127.0.0.1:8000/ws/some_path/
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxNDQ5MTg3LCJpYXQiOjE3MzE0NDU1ODcsImp0aSI6ImQyODRlZTE2OTQyYzQ0ODg5ZWIxMjE3ZWNkOTk5MmI3IiwidXNlcl9pZCI6M30.s456GPatVon_OWWnnOn9H1TxpZ0u2yByWOu8zRFbKEk

### Envoyer un message via WebSocket (une fois connecté)
SEND ws://127.0.0.1:8000/ws/some_path/
Content-Type: application/json

{
    "type": "websocket.send",
    "text": "Hello, WebSocket!"
}