### Création/Mise à jour d'une image de profil

# Scénario 1 : Upload avec un nouvel utilisateur
POST http://127.0.0.1:8001/api/media/upload/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwODM0MTQwLCJpYXQiOjE3MzA4MzA1NDAsImp0aSI6IjMxNDIwODA5ZGM0NTQ3ZGI4NzViYjEwOTgyYTAxMjNmIiwidXNlcl9pZCI6Mn0.lASarlzTnQS9Y16357_QUJrmgk7VqAwag8DxsEwQ1n8
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="photo_profil.jpg"
Content-Type: image/jpeg

< /mnt/nfs/homes/soutin/Pictures/spider_man_meme.jpg
------WebKitFormBoundary--
###

# Get image
GET http://127.0.0.1:8001/api/media/profile-images/jd/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwODM0MTQwLCJpYXQiOjE3MzA4MzA1NDAsImp0aSI6IjMxNDIwODA5ZGM0NTQ3ZGI4NzViYjEwOTgyYTAxMjNmIiwidXNlcl9pZCI6Mn0.lASarlzTnQS9Y16357_QUJrmgk7VqAwag8DxsEwQ1n8
###

GET http://127.0.0.1:8001/api/media/profile-images/jd/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwODMxMDEyLCJpYXQiOjE3MzA4Mjc0MTIsImp0aSI6ImE5ODZmMTkyMDJmMDQyNDliNWViMjVlMjcxYTAxNGQxIiwidXNlcl9pZCI6Mn0.QpV0E34hOiR0SEZpHDnOgKIByzx_Q39RWVxlEKc3HXc
###

# Delete image
DELETE  http://127.0.0.1:8001/api/media/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwODM0MTQwLCJpYXQiOjE3MzA4MzA1NDAsImp0aSI6IjMxNDIwODA5ZGM0NTQ3ZGI4NzViYjEwOTgyYTAxMjNmIiwidXNlcl9pZCI6Mn0.lASarlzTnQS9Y16357_QUJrmgk7VqAwag8DxsEwQ1n8
###


### Scénario 2 : Upload pour un utilisateur existant
POST http://127.0.0.1:8001/api/media/upload/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwODMxMDEyLCJpYXQiOjE3MzA4Mjc0MTIsImp0aSI6ImE5ODZmMTkyMDJmMDQyNDliNWViMjVlMjcxYTAxNGQxIiwidXNlcl9pZCI6Mn0.QpV0E34hOiR0SEZpHDnOgKIByzx_Q39RWVxlEKc3HXc
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="nouvelle_photo.gif"
Content-Type: image/png

< /mnt/nfs/homes/soutin/Pictures/non-mario.gif
------WebKitFormBoundary--

### Scénario 3 : Upload sans image (devrait échouer si image obligatoire)
POST http://localhost:8000/api/profile-image/upload/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="username"

utilisateur_sans_image
------WebKitFormBoundary--

### Scénario 4 : Upload avec une image trop volumineuse
POST http://localhost:8000/api/profile-image/upload/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="username"

utilisateur_grosse_image
------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="image_trop_grosse.jpg"
Content-Type: image/jpeg

< ./chemin/vers/image/volumineuse.jpg
------WebKitFormBoundary--