# Generated by Django 5.1.2 on 2024-11-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NoStudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Student',
            field=models.BooleanField(default=False),
        ),
    ]
