services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - my_network


  chat:
    build:
      context: ./docker
    ports:
      - "8002:8000"
    volumes:
      - .:/app
      - ./docker:/app/docker
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    env_file:
      - .env
    networks:
      my_network:
        aliases:
          - chat
    entrypoint: ["/app/docker/entrypoint_dev.sh"]
    depends_on:
      - redis

networks:
  my_network:
    external: true
