services:
  # db-chat:
  #   image: postgres:17
  #   ports:
  #     - "5434:5432"
  #   env_file:
  #     - .env
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - my_network

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - my_network

  chat:
    build:
      context: ./docker
    ports:
      - "8002:8000"
    volumes:
      - .:/app
      - ./docker:/app/docker
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    env_file:
      - .env
    networks:
      my_network:
        aliases:
          - chat
    entrypoint: ["/app/docker/entrypoint_dev.sh"]
    depends_on:
      - redis

volumes:
  postgres_data:

networks:
  my_network:
    external: true
