services:
  db-auth:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - postgres_data:/var/lib/postgresql/data
    entrypoint: ["/app/docker/entrypoint_db.sh"]

  auth:
    build:
      context: ./docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./docker:/app/docker
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    env_file:
      - .env
    entrypoint: ["/app/docker/entrypoint_dev.sh"]
    depends_on:
      - db-auth


volumes:
  postgres_data: