services:
  db-media:
    image: postgres:13
    ports:
      - "5434:5432"
    volumes:
      - .:/app
      - postgres_data:/var/lib/postgresql/data
    entrypoint: ["/app/docker/entrypoint_db.sh"]
    networks:
      - my_network


  media:
    build:
      context: ./docker
    ports:
      - "8002:8000"
    volumes:
      - .:/app
      - ./docker:/app/docker
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    env_file:
      - .env
    networks:
      my_network:
        aliases:
          - media
    entrypoint: ["/app/docker/entrypoint_dev.sh"]
    depends_on:
      - db-media

volumes:
  postgres_data:

networks:
  my_network:
    external: true
