### Login
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "reset.pass.ponggame@gmail.com",
    "password": "palestin"
}

### Signup
POST http://127.0.0.1:8000/api/auth/signup/
Content-Type: application/json

{
    "username": "jdennis",
    "password": "bret",
    "password2": "bret",
    "email": "reset.pass.ponggame@gmail.com"
}

### Refresh Token
POST http://127.0.0.1:8000/api/auth/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMDI4MTQxMywiaWF0IjoxNzI5Njc2NjEzLCJqdGkiOiJlODIwNDg3NTgxMjU0Mzg2OGQzNmM0YTEwMzczMWIxNyIsInVzZXJfaWQiOjV9.jTOy4cxp-B1OQTxldEybhVKHSsIsGkwDd5LH155nyXQ"
}

### Request Password Reset
POST http://127.0.0.1:8000/api/auth/password/reset/
Content-Type: application/json

{
    "email": "reset.pass.ponggame@gmail.com"
}

### Confirm Password Reset
POST http://127.0.0.1:8000/api/auth/password/reset/confirm/Mg/cfnhn8-6526e51095b178fa8d48f420e5b2e6bc/
Content-Type: application/json

{
    "new_password": "palestin"
}