### Login
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "bilel",
    "password": "Algerie93"
}

### Signup
POST http://127.0.0.1:8000/api/auth/signup/
Content-Type: application/json

{
    "username": "bilel",
    "password": "Algerie93",
    "password2": "Algerie93",
    "email": "reset.pass.ponggame@gmail.com"
}

### Refresh Token
POST http://127.0.0.1:8000/api/auth/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMDI4MTQxMywiaWF0IjoxNzI5Njc2NjEzLCJqdGkiOiJlODIwNDg3NTgxMjU0Mzg2OGQzNmM0YTEwMzczMWIxNyIsInVzZXJfaWQiOjV9.jTOy4cxp-B1OQTxldEybhVKHSsIsGkwDd5LH155nyXQ"
}

### Request Password Reset
POST http://127.0.0.1:8000/api/auth/password/reset/
Content-Type: application/json

{
    "email": "reset.pass.ponggame@gmail.com"
}

### Confirm Password Reset
POST http://127.0.0.1:8000/api/auth/password/reset/confirm/Mg/cfnhn8-6526e51095b178fa8d48f420e5b2e6bc/
Content-Type: application/json

{
    "new_password": "palestin"
}

### Confirm Password Reset
POST http://127.0.0.1:8000/api/auth/password/change/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjE5NDM4LCJpYXQiOjE3MzAyMTU4MzgsImp0aSI6IjkwYjYyOTFiYzY5YjRjODlhYzViNTlkNGJjYTFmNzgyIiwidXNlcl9pZCI6MX0.dfoBLpa6WHpZt4T9Qoi2NJuRbaPs6DyJo6wHJe3nHzc

{
    "old_password": "Algerie93",
    "new_password": "palestine"
}

### Logout
POST http://127.0.0.1:8000/api/auth/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjI2NTQxLCJpYXQiOjE3MzAyMjI5NDEsImp0aSI6ImU0M2E0OGNkYTdjODRlMDFiNzYzOGE4NWFiYTNlZmJjIiwidXNlcl9pZCI6M30.Hpq15vKuxFjUHGXAAtaLdjFNxKnBHyl7mXTi59jyzEY

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjI2NTQxLCJpYXQiOjE3MzAyMjI5NDEsImp0aSI6ImU0M2E0OGNkYTdjODRlMDFiNzYzOGE4NWFiYTNlZmJjIiwidXNlcl9pZCI6M30.Hpq15vKuxFjUHGXAAtaLdjFNxKnBHyl7mXTi59jyzEY"
}

### Token verify

POST http://127.0.0.1:8000/api/auth/token/validate/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjI1MDU3LCJpYXQiOjE3MzAyMjE0NTcsImp0aSI6IjhjODliYjExMGNkNDQ2ZDc5ZThhMzA2YmVlY2RiMzgyIiwidXNlcl9pZCI6M30.obZ6W0e66Sod_py8ZRQxzRgd5yvH6i44uhtTP-3jWVw

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjI1MDU3LCJpYXQiOjE3MzAyMjE0NTcsImp0aSI6IjhjODliYjExMGNkNDQ2ZDc5ZThhMzA2YmVlY2RiMzgyIiwidXNlcl9pZCI6M30.obZ6W0e66Sod_py8ZRQxzRgd5yvH6i44uhtTP-3jWVw"
}