# Generated by Django 5.1.2 on 2024-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('nb_game', models.IntegerField(default=0)),
                ('nb_win', models.IntegerField(default=0)),
                ('nb_losses', models.IntegerField(default=0)),
                ('avg_duration', models.IntegerField(default=0)),
            ],
        ),
    ]
