# Generated by Django 5.1.2 on 2024-11-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagementService', '0002_alter_userprofile_avg_duration_matchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_1', to='UserManagementService.userprofile')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_2', to='UserManagementService.userprofile')),
            ],
            options={
                'unique_together': {('user_1', 'user_2')},
            },
        ),
    ]
