# Generated by Django 5.1.2 on 2024-10-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaService', '0002_alter_userprofileimage_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileimage',
            old_name='username',
            new_name='user',
        ),
    ]
