services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web_dev:
    build:
      context: ./docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./docker:/app/docker
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    env_file:
      - .env
    entrypoint: ["/app/docker/entrypoint_dev.sh"]
    depends_on:
      - db

  web_prod:
    build:
      context: ./docker
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./docker:/app/docker
    environment:
      - DEBUG=False
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    entrypoint: ["/app/docker/entrypoint_prod.sh"]
    depends_on:
      - db

volumes:
  postgres_data: