services:
  wsmanagement:
    build:
      context: ./docker
    ports:
      - "8005:8000"
    volumes:
      - .:/app
      - ./docker:/app/docker
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    env_file:
      - .env
    networks:
      my_network:
        aliases:
          - websocketmanagement
    entrypoint: ["/app/docker/entrypoint_dev.sh"]

volumes:
  postgres_data:

networks:
  my_network:
    external: true
